import cityImg from "../assets/images/city.jpg"

export const citiesData = [
    {
        id: 1,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 2,
        img: cityImg,
        name: "Lisbon",
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 3,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 4,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 5,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 6,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 7,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 8,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 9,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 10,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 11,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 12,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 13,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 14,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 15,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 16,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 17,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 18,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 19,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 20,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 21,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 22,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 23,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 24,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 25,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 26,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 27,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 28,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 29,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 30,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 31,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    },
    {
        id: 32,
        name: "Lisbon",
        img: cityImg,
        internetSpeed: 29,
        currentTemperature: 27,
        humidity: 11,
        monthlyCost: 2156,
        overALLRating: 75,
        cost: 80,
        internetRating: 75,
        fun: 70,
        safety: 65
    }
]